stages:
 - build

build-package:
  stage: build
  image: docker.io/multiarch/ubuntu-debootstrap:amd64-xenial-slim
  script:
    - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10no-recommends
    - echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/10no-suggests
    # i386/amd64 Ubuntu only
    - /bin/sed -i 's/main/main restricted universe/' /etc/apt/sources.list
    - apt-get update && apt-get install -y build-essential ca-certificates devscripts dpkg-dev equivs lsb-release wget
    - echo "deb http://amp.wand.net.nz/debian/ `lsb_release -c -s` main" > /etc/apt/sources.list.d/amplet2.list
    - wget -O- http://amp.wand.net.nz/debian/pubkey.gpg | apt-key add -
    - apt-get update && apt-get upgrade -y
    - mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='brendonj@waikato.ac.nz'
    - export DEBFULLNAME='Brendon Jones'
    # TODO use my proper changelog, just remove this line?
    #- debchange --newversion ${CI_COMMIT_REF_NAME} -b "New upstream release"
    - fakeroot debian/rules binary
    - mkdir built-packages || true
    - mv ../*.deb built-packages/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags
