stages:
 - build

.generic_apt_build_template: &generic_apt_build
  mk-build-deps -i -r -t 'apt-get -f -y --force-yes' &&
  export DEBEMAIL='brendonj@waikato.ac.nz' &&
  export DEBFULLNAME='Brendon Jones' &&
  fakeroot debian/rules binary &&
  mkdir built-packages || true &&
  mv ../*.deb built-packages/

.generic_apt_setup_template: &generic_apt_setup
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10no-recommends &&
  echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/10no-suggests

.ubuntu_apt_setup_template: &ubuntu_apt_setup
  /bin/sed -i 's/main/main restricted universe/' /etc/apt/sources.list

.xenial_cross_setup_template: &xenial_cross_setup
  echo "deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe" >> /etc/apt/sources.list &&
  echo "deb http://ports.ubuntu.com/ubuntu-ports xenial-updates main restricted universe" >> /etc/apt/sources.list &&
  echo "deb http://ports.ubuntu.com/ubuntu-ports xenial-security main restricted universe" >> /etc/apt/sources.list

.generic_apt_dependencies_template: &generic_apt_dependencies
  apt-get update &&
  apt-get install -y build-essential ca-certificates devscripts dpkg-dev equivs  gnupg lsb-release wget &&
  echo "deb http://amp.wand.net.nz/debian/ `lsb_release -c -s` main" > /etc/apt/sources.list.d/amplet2.list &&
  wget -O- http://amp.wand.net.nz/debian/pubkey.gpg | apt-key add - &&
  apt-get update &&
  apt-get upgrade -y

build-bionic:
  stage: build
  image: docker.io/multiarch/ubuntu-debootstrap:amd64-bionic-slim
  script:
    - *generic_apt_setup
    - *ubuntu_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-bionic-arm64:
  stage: build
  image: docker.io/multiarch/ubuntu-debootstrap:arm64-bionic-slim
  script:
    - *generic_apt_setup
    - *ubuntu_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags
  tags:
    - arm64

build-xenial:
  stage: build
  image: docker.io/multiarch/ubuntu-debootstrap:amd64-xenial-slim
  script:
    - *generic_apt_setup
    - *ubuntu_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-xenial-arm64:
  stage: build
  image: docker.io/multiarch/ubuntu-debootstrap:arm64-xenial-slim
  script:
    - *generic_apt_setup
    - *ubuntu_apt_setup
    - *xenial_cross_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags
  tags:
    - arm64

build-stretch:
  stage: build
  image: docker.io/multiarch/debian-debootstrap:amd64-stretch-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-stretch-arm64:
  stage: build
  image: docker.io/multiarch/debian-debootstrap:arm64-stretch-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags
  tags:
    - arm64

build-jessie-amd64:
  stage: build
  image: multiarch/debian-debootstrap:amd64-jessie-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-jessie-arm64:
  stage: build
  image: multiarch/debian-debootstrap:arm64-jessie-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-jessie-armhf:
  stage: build
  image: multiarch/debian-debootstrap:armhf-jessie-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags

build-jessie-i386:
  stage: build
  image: multiarch/debian-debootstrap:i386-jessie-slim
  script:
    - *generic_apt_setup
    - *generic_apt_dependencies
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 hour
  only:
    - tags
