extraction:
    cpp:
        after_prepare:
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent_3.0.1-1_amd64.deb
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent-dev_3.0.1-1_amd64.deb
            - dpkg -x libwandevent_3.0.1-1_amd64.deb /tmp/
            - dpkg -x libwandevent-dev_3.0.1-1_amd64.deb /tmp/
            - ./bootstrap.sh

        configure:
            command: CFLAGS=-I/tmp/usr/infclude/ LD_FLAGS=-L/tmp/usr/lib/ ./configure
