extraction:
    cpp:
        after_prepare:
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent_3.0.1-1_amd64.deb
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent-dev_3.0.1-1_amd64.deb
            - dpkg -i libwandevent_3.0.1-1_amd64.deb
            - dpkg -i libwandevent-dev_3.0.1-1_amd64.deb
