extraction:
    cpp:
        after_prepare:
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent_3.0.1-1_amd64.deb
            - wget http://amp.wand.net.nz/debian/pool/bionic/main/libw/libwandevent/libwandevent-dev_3.0.1-1_amd64.deb
            - dpkg -x libwandevent_3.0.1-1_amd64.deb .
            - dpkg -x libwandevent-dev_3.0.1-1_amd64.deb .

        configure:
            command: CFLAGS=-I`pwd`/usr/include/ LD_FLAGS=-L`pwd`/usr/lib/ ./configure
